/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Cheap enough to call every few seconds. Touches nothing.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Confirms the pricing library imports and the cache is addressable.
         */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Build and model metadata
         * @description What this build is and what it can do. Useful for debugging a deployment.
         */
        get: operations["meta_api_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/price": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Price with one model
         * @description Price a contract with a single model, returning all five Greeks.
         *
         *     Requesting American exercise from Black-Scholes or Monte Carlo returns 422 naming
         *     the constraint. Returning a European price for an American contract would be
         *     silently wrong, which is worse than a refusal.
         */
        post: operations["price_api_v1_price_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Price with every model
         * @description Run all three models on identical inputs and measure them against a reference.
         *
         *     For a European contract the reference is the closed form. For an American one
         *     there is no closed form, so a high-resolution lattice stands in and the other two
         *     models report why they declined rather than failing the whole request.
         */
        post: operations["compare_api_v1_compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/convergence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Convergence sweeps
         * @description Both numerical models plotted against the exact answer as resolution increases.
         *
         *     The two signatures are visibly different: the lattice oscillates around the true
         *     price with decaying amplitude, while simulation converges stochastically with its
         *     confidence band narrowing as 1/sqrt(n).
         */
        post: operations["convergence_sweep_api_v1_convergence_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payoff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Payoff and profit curve
         * @description Payoff at expiry and profit after the premium, across a grid of spot prices.
         */
        post: operations["payoff_api_v1_payoff_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sensitivity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * A Greek plotted against spot
         * @description One Greek across a spot grid, everything else held fixed.
         */
        post: operations["sensitivity_api_v1_sensitivity_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/paths": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sample GBM trajectories
         * @description A handful of simulated price paths, purely to illustrate what Monte Carlo does.
         *
         *     Deliberately separate from pricing: never simulate a million trajectories to draw
         *     a hundred lines.
         */
        post: operations["paths_api_v1_paths_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/implied-vol": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Solve for implied volatility
         * @description Back out the volatility that reproduces an observed market price.
         *
         *     Brent's method on a bracket rather than Newton-Raphson: vega collapses deep in
         *     and out of the money, which is exactly where Newton becomes unstable.
         */
        post: operations["implied_vol_api_v1_implied_vol_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Spot price and realised volatility for a ticker
         * @description Fetch a quote, served from a 15-minute cache where possible.
         *
         *     ``realised_vol_30d`` is the annualised standard deviation of the last 30 daily log
         *     returns, scaled by sqrt(252). It is a reasonable starting point for the volatility
         *     input, not a substitute for an implied vol, and the UI presents it as such.
         */
        get: operations["quote_api_v1_market__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BinomialPoint */
        BinomialPoint: {
            /** Steps */
            steps: number;
            /** Price */
            price: number;
            /** Error */
            error: number;
        };
        /** CompareRequest */
        CompareRequest: {
            option: components["schemas"]["OptionInput"];
            params?: components["schemas"]["ModelParams"];
        };
        /** CompareResponse */
        CompareResponse: {
            reference_model: components["schemas"]["Model"];
            /** Reference Price */
            reference_price: number;
            /** Results */
            results: components["schemas"]["ComparisonRow"][];
            /** Unsupported */
            unsupported?: components["schemas"]["UnsupportedModel"][];
        };
        /**
         * ComparisonRow
         * @description One model's result, measured against the reference price.
         */
        ComparisonRow: {
            model: components["schemas"]["Model"];
            /** Price */
            price: number;
            greeks: components["schemas"]["GreeksOut"];
            /** Compute Ms */
            compute_ms: number;
            /** Standard Error */
            standard_error?: number | null;
            /** Confidence Interval */
            confidence_interval?: [
                number,
                number
            ] | null;
            /** Diagnostics */
            diagnostics?: {
                [key: string]: unknown;
            };
            /**
             * Abs Error
             * @description Signed difference from the reference price
             */
            abs_error: number;
            /**
             * Rel Error
             * @description abs_error as a fraction of the reference price
             */
            rel_error: number;
        };
        /** ConvergenceRequest */
        ConvergenceRequest: {
            option: components["schemas"]["OptionInput"];
            /**
             * Max Steps
             * @default 200
             */
            max_steps: number;
            /**
             * Max Paths
             * @default 200000
             */
            max_paths: number;
            /**
             * Seed
             * @default 42
             */
            seed: number;
        };
        /** ConvergenceResponse */
        ConvergenceResponse: {
            /** Reference Price */
            reference_price: number;
            reference_model: components["schemas"]["Model"];
            /** Binomial */
            binomial: components["schemas"]["BinomialPoint"][];
            /** Monte Carlo */
            monte_carlo: components["schemas"]["MonteCarloPoint"][];
        };
        /**
         * Exercise
         * @enum {string}
         */
        Exercise: "european" | "american";
        /**
         * GreeksOut
         * @description Raw derivatives. Vega and rho are per 1.00 absolute move; theta is per year.
         */
        GreeksOut: {
            /** Delta */
            delta: number;
            /** Gamma */
            gamma: number;
            /** Vega */
            vega: number;
            /** Theta */
            theta: number;
            /** Rho */
            rho: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** ImpliedVolRequest */
        ImpliedVolRequest: {
            /** @description volatility is ignored; every other field is used */
            option: components["schemas"]["OptionInput"];
            /** Market Price */
            market_price: number;
        };
        /** ImpliedVolResponse */
        ImpliedVolResponse: {
            /** Implied Volatility */
            implied_volatility: number;
            /** Market Price */
            market_price: number;
            /**
             * Reprice Check
             * @description Closed-form price at the solved volatility
             */
            reprice_check: number;
        };
        /** MarketQuote */
        MarketQuote: {
            /** Symbol */
            symbol: string;
            /** Spot */
            spot: number;
            /** Currency */
            currency: string;
            /** Realised Vol 30D */
            realised_vol_30d: number | null;
            /** As Of */
            as_of: string;
            /** Cache Hit */
            cache_hit: boolean;
            /** Source */
            source: string;
        };
        /** MetaResponse */
        MetaResponse: {
            /** App Name */
            app_name: string;
            /** Version */
            version: string;
            /** Git Sha */
            git_sha: string;
            /** Build Time */
            build_time: string;
            /** Market Data Enabled */
            market_data_enabled: boolean;
            /** Models */
            models: components["schemas"]["ModelInfo"][];
        };
        /**
         * Model
         * @enum {string}
         */
        Model: "black_scholes" | "binomial" | "monte_carlo";
        /** ModelInfo */
        ModelInfo: {
            id: components["schemas"]["Model"];
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Supports American */
            supports_american: boolean;
            /** Stochastic */
            stochastic: boolean;
        };
        /**
         * ModelParams
         * @description Numerical settings. Ignored by the closed form, which has none.
         */
        ModelParams: {
            /**
             * Steps
             * @description Binomial lattice steps
             * @default 500
             */
            steps: number;
            /**
             * Paths
             * @description Monte Carlo sample paths
             * @default 100000
             */
            paths: number;
            /**
             * Seed
             * @description RNG seed; results are reproducible
             * @default 42
             */
            seed: number;
            /**
             * Antithetic
             * @description Pair each draw Z with -Z
             * @default true
             */
            antithetic: boolean;
            /**
             * Control Variate
             * @description Regress the payoff on the discounted terminal price
             * @default true
             */
            control_variate: boolean;
        };
        /** MonteCarloPoint */
        MonteCarloPoint: {
            /** Paths */
            paths: number;
            /** Price */
            price: number;
            /** Standard Error */
            standard_error: number;
            /** Ci Low */
            ci_low: number;
            /** Ci High */
            ci_high: number;
            /** Error */
            error: number;
        };
        /**
         * OptionInput
         * @description A contract plus the market state needed to price it.
         * @example {
         *       "dividend_yield": 0,
         *       "exercise": "european",
         *       "option_type": "call",
         *       "risk_free_rate": 0.05,
         *       "spot": 100,
         *       "strike": 100,
         *       "time_to_expiry": 1,
         *       "volatility": 0.2
         *     }
         */
        OptionInput: {
            /**
             * Spot
             * @description Current price of the underlying
             */
            spot: number;
            /**
             * Strike
             * @description Exercise price
             */
            strike: number;
            /**
             * Time To Expiry
             * @description Years until expiry (0.25 = three months)
             */
            time_to_expiry: number;
            /**
             * Risk Free Rate
             * @description Continuously compounded annual rate, 0.05 = 5%
             */
            risk_free_rate: number;
            /**
             * Volatility
             * @description Annualised volatility, 0.2 = 20%
             */
            volatility: number;
            /**
             * Dividend Yield
             * @description Continuous dividend yield
             * @default 0
             */
            dividend_yield: number;
            /** @default call */
            option_type: components["schemas"]["OptionType"];
            /** @default european */
            exercise: components["schemas"]["Exercise"];
        };
        /**
         * OptionType
         * @enum {string}
         */
        OptionType: "call" | "put";
        /** PathsRequest */
        PathsRequest: {
            option: components["schemas"]["OptionInput"];
            /**
             * N Paths
             * @default 100
             */
            n_paths: number;
            /**
             * N Steps
             * @default 100
             */
            n_steps: number;
            /**
             * Seed
             * @default 42
             */
            seed: number;
        };
        /** PathsResponse */
        PathsResponse: {
            /** Times */
            times: number[];
            /** Paths */
            paths: number[][];
            /** Strike */
            strike: number;
            /** Terminal Mean */
            terminal_mean: number;
        };
        /** PayoffRequest */
        PayoffRequest: {
            option: components["schemas"]["OptionInput"];
            /**
             * Points
             * @default 121
             */
            points: number;
            /**
             * Span
             * @description Grid half-width as a fraction of strike
             * @default 0.6
             */
            span: number;
        };
        /** PayoffResponse */
        PayoffResponse: {
            /** Spots */
            spots: number[];
            /** Payoffs */
            payoffs: number[];
            /** Profits */
            profits: number[];
            /** Breakeven */
            breakeven: number;
            /** Premium */
            premium: number;
            /** Strike */
            strike: number;
            /** Current Spot */
            current_spot: number;
        };
        /** PriceRequest */
        PriceRequest: {
            option: components["schemas"]["OptionInput"];
            /** @default black_scholes */
            model: components["schemas"]["Model"];
            params?: components["schemas"]["ModelParams"];
        };
        /** PricingResultOut */
        PricingResultOut: {
            model: components["schemas"]["Model"];
            /** Price */
            price: number;
            greeks: components["schemas"]["GreeksOut"];
            /** Compute Ms */
            compute_ms: number;
            /** Standard Error */
            standard_error?: number | null;
            /** Confidence Interval */
            confidence_interval?: [
                number,
                number
            ] | null;
            /** Diagnostics */
            diagnostics?: {
                [key: string]: unknown;
            };
        };
        /** ReadyResponse */
        ReadyResponse: {
            /** Status */
            status: string;
            /** Checks */
            checks: {
                [key: string]: string;
            };
        };
        /** SensitivityRequest */
        SensitivityRequest: {
            option: components["schemas"]["OptionInput"];
            /**
             * Greek
             * @default delta
             * @enum {string}
             */
            greek: "delta" | "gamma" | "vega" | "theta" | "rho";
            /** @default black_scholes */
            model: components["schemas"]["Model"];
            /**
             * Points
             * @default 81
             */
            points: number;
            /**
             * Span
             * @default 0.5
             */
            span: number;
            /**
             * Steps
             * @default 200
             */
            steps: number;
        };
        /** SensitivityResponse */
        SensitivityResponse: {
            /**
             * Greek
             * @enum {string}
             */
            greek: "delta" | "gamma" | "vega" | "theta" | "rho";
            model: components["schemas"]["Model"];
            /** Spots */
            spots: number[];
            /** Values */
            values: number[];
            /** Current Spot */
            current_spot: number;
            /** Strike */
            strike: number;
        };
        /**
         * UnsupportedModel
         * @description A model that cannot price this contract, and why.
         *
         *     Returned alongside the results rather than as an error: asking three models to
         *     price an American option is a reasonable request, and two of them declining is
         *     information, not a failure.
         */
        UnsupportedModel: {
            model: components["schemas"]["Model"];
            /** Reason */
            reason: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
        };
    };
    meta_api_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaResponse"];
                };
            };
        };
    };
    price_api_v1_price_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PriceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PricingResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_api_v1_compare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompareRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    convergence_sweep_api_v1_convergence_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConvergenceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConvergenceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    payoff_api_v1_payoff_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PayoffRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PayoffResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sensitivity_api_v1_sensitivity_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SensitivityRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SensitivityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    paths_api_v1_paths_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PathsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PathsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    implied_vol_api_v1_implied_vol_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImpliedVolRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImpliedVolResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quote_api_v1_market__symbol__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketQuote"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Upstream unavailable; enter values manually */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
